<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.zap</groupId>
    <artifactId>zap-java</artifactId>
    <packaging>pom</packaging>
    <version>0.1.17-SNAPSHOT</version>
    <name>ZAP for Java</name>
    <url>https://zap-proto.io/</url>
    <modules>
      <module>runtime</module>
      <module>compiler</module>
      <module>examples</module>
      <module>benchmark</module>
    </modules>
    <licenses>
        <license>
            <name>MIT</name>
            <url>http://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <url>git@github.com:zap-proto/java.git</url>
        <connection>scm:git@github.com:zap-proto/java.git</connection>
    </scm>
    <developers>
        <developer>
            <id>dwrensha</id>
            <name>David Renshaw</name>
            <url>https://github.com/dwrensha</url>
        </developer>
    </developers>
</project>
