<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.zap</groupId>
    <artifactId>compiler</artifactId>
    <packaging>jar</packaging>
    <description>schema compiler plugin for java</description>
    <version>0.1.17-SNAPSHOT</version>
    <name>zapc-java</name>
    <organization>
        <name>org.zap</name>
    </organization>
    <url>https://zap-proto.io/</url>
    <licenses>
        <license>
            <name>MIT</name>
            <url>http://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <url>git@github.com:zap-proto/java.git</url>
        <connection>scm:git@github.com:zap-proto/java.git</connection>
    </scm>
    <developers>
        <developer>
            <id>dwrensha</id>
            <name>David Renshaw</name>
            <url>https://github.com/dwrensha</url>
        </developer>
    </developers>
    <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <maven.compiler.source>1.8</maven.compiler.source>
      <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.14.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
          <groupId>org.zap</groupId>
          <artifactId>runtime</artifactId>
          <version>0.1.17-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.15.0</version>
          <configuration>
            <compilerArgument>-Xlint:unchecked</compilerArgument>
          </configuration>
        </plugin>

        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>3.2.0</version>
          <executions>

            <execution>
              <id>compile</id>
              <phase>compile</phase>
              <configuration>
                <target>
                  <exec executable="make" failonerror="true">
                    <arg value="--directory=.."/>
                  </exec>
                </target>
              </configuration>
              <goals>
                <goal>run</goal>
              </goals>
            </execution>

            <execution>
              <id>generate-test-sources</id>
              <phase>generate-test-sources</phase>
              <configuration>
                <target>
                  <mkdir dir="src/test/generated"/>
                  <exec executable="zap" failonerror="true">
                    <arg value="compile"/>
                    <arg value="-I"/>
                    <arg value="src/main/schema/"/>
                    <arg value="--src-prefix=src/test/schema/"/>
                    <arg value="-o../zapc-java:src/test/generated"/>
                    <arg value="src/test/schema/test.zap"/>
                    <arg value="src/test/schema/test-import.zap"/>
                  </exec>
                </target>
              </configuration>
              <goals>
                <goal>run</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>3.6.1</version>
          <executions>
            <execution>
              <id>add-generated-test-sources</id>
              <phase>generate-test-sources</phase>
              <goals>
                <goal>add-test-source</goal>
              </goals>
              <configuration>
                <sources>
                  <source>src/test/generated</source>
                </sources>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
</project>
